//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHSCBRAEntryStatu
    {
        public long Id { get; set; }
        public Nullable<long> SiteId { get; set; }
        public string BHSName { get; set; }
        public string SectionName { get; set; }
        public string DeviceType { get; set; }
        public int DeviceId { get; set; }
        public string AreaName { get; set; }
        public string QueueName { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Token { get; set; }
        public Nullable<int> StatusFlags { get; set; }
        public int QueueId { get; set; }
        public int OutOfGauge { get; set; }
        public int NoResponse { get; set; }
        public int EDSError { get; set; }
        public int EDSTimeout { get; set; }
        public int EDSAlarm { get; set; }
        public int EDSClear { get; set; }
        public int UnknownLostInTracking { get; set; }
        public int UnknownLengthError { get; set; }
        public int UnknownDuplicateToken { get; set; }
        public int UnknownOther { get; set; }
        public Nullable<int> CBRACleared { get; set; }
        public Nullable<long> SectionSystemId { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
