//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHSJamAlarm
    {
        public long Id { get; set; }
        public long SiteId { get; set; }
        public int InstanceId { get; set; }
        public System.DateTime AlarmDateTime { get; set; }
        public string AlarmColor { get; set; }
        public Nullable<System.DateTime> AcknowledgeTime { get; set; }
        public string AcknowledgedBy { get; set; }
        public string AcknowledColor { get; set; }
        public string Location { get; set; }
        public Nullable<long> LocationSystemId { get; set; }
        public string Alarm { get; set; }
        public Nullable<System.DateTime> ReturnToNormalTime { get; set; }
        public string NormalColor { get; set; }
        public string DeviceTypeName { get; set; }
        public string BHSName { get; set; }
        public string DeviceName { get; set; }
        public Nullable<long> DeviceSystemId { get; set; }
        public int IsAlarmNested { get; set; }
        public System.DateTime MinValueTimeStamp { get; set; }
        public System.DateTime MaxValueTimeStamp { get; set; }
        public long BagThroughput { get; set; }
        public string TypesName { get; set; }
        public string TransactionType { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
