//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    
    public partial class BHSLocationThroughput_Result1
    {
        public Nullable<long> SiteId { get; set; }
        public string Section { get; set; }
        public Nullable<long> BagCount { get; set; }
    }
}
