//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorizedActivity
    {
        public long Id { get; set; }
        public Nullable<long> AuthorizableActivityId { get; set; }
        public Nullable<long> iOPSUserId { get; set; }
    
        public virtual AuthorizableActivity AuthorizableActivity { get; set; }
        public virtual iOPSUser iOPSUser { get; set; }
    }
}
