//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetCustomTagDisplayOrder
    {
        public long Id { get; set; }
        public Nullable<long> iOPSUserId { get; set; }
        public Nullable<long> WidgetId { get; set; }
        public Nullable<long> JBTStandardObservationId { get; set; }
        public Nullable<int> Ordinal { get; set; }
    
        public virtual Widget Widget { get; set; }
        public virtual iOPSUser iOPSUser { get; set; }
        public virtual JBTStandardObservation JBTStandardObservation { get; set; }
    }
}
