//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetModel()
        {
            this.Assets = new HashSet<Asset>();
            this.AssetModelImages = new HashSet<AssetModelImage>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public string GraphicsPath { get; set; }
        public Nullable<int> BlowerCount { get; set; }
        public Nullable<int> CompressorCount { get; set; }
        public Nullable<int> HeaterCount { get; set; }
        public Nullable<int> FanCount { get; set; }
        public Nullable<bool> HasAirflowArrows { get; set; }
        public string Description { get; set; }
        public string BaseImageName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetModelImage> AssetModelImages { get; set; }
    }
}
