//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHSDeviceLocationCarrierMap
    {
        public long Id { get; set; }
        public long DeviceLocationId { get; set; }
        public long CarrierId { get; set; }
    
        public virtual BHSCarrier BHSCarrier { get; set; }
        public virtual BHSDeviceLocation DeviceLocation { get; set; }
    }
}
