//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dashboard()
        {
            this.Widgets = new HashSet<Widget>();
            this.AssociatedWidgets = new HashSet<Widget>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsAdminFixed { get; set; }
        public Nullable<long> LastModifiedUserId { get; set; }
        public Nullable<bool> IsInitialNameless { get; set; }
        public string Description { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<System.DateTime> CustomStartDate { get; set; }
        public Nullable<System.DateTime> CustomEndDate { get; set; }
        public Nullable<long> TimeScopeId { get; set; }
        public Nullable<long> ParentDashboardId { get; set; }
    
        public virtual iOPSUser iOPSUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widget> Widgets { get; set; }
        public virtual DashboardTimeScope DashboardTimeScope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widget> AssociatedWidgets { get; set; }
    }
}
