//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseMailQueue
    {
        public long Id { get; set; }
        public string ProfileName { get; set; }
        public string Recipients { get; set; }
        public string CopyRecipients { get; set; }
        public string BlindCopyRecipients { get; set; }
        public string FromAddress { get; set; }
        public string ReplyTo { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string BodyFormat { get; set; }
        public string Importance { get; set; }
        public string Sensitivity { get; set; }
        public string FileAttachments { get; set; }
        public string Query { get; set; }
        public string ExecuteQueryDatabase { get; set; }
        public Nullable<bool> AttachQueryResultAsFile { get; set; }
        public string QueryAttachmentFilename { get; set; }
        public Nullable<bool> QueryResultHeader { get; set; }
        public Nullable<int> QueryResultWidth { get; set; }
        public string QueryResultSeparator { get; set; }
        public Nullable<bool> ExcludeQueryOutput { get; set; }
        public Nullable<bool> AppendQueryError { get; set; }
        public Nullable<bool> QueryNoTruncate { get; set; }
        public Nullable<bool> QueryResultNoPadding { get; set; }
        public Nullable<int> MailItemId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string SentStatus { get; set; }
        public Nullable<int> Result { get; set; }
    }
}
