//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iOPSUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iOPSUser()
        {
            this.UserAuthorizedActivities = new HashSet<UserAuthorizedActivity>();
            this.UserEventLogs = new HashSet<UserEventLog>();
            this.CompanyDataReaders = new HashSet<CompanyDataReader>();
            this.SiteDataReaders = new HashSet<SiteDataReader>();
            this.Dashboards = new HashSet<Dashboard>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PersonId { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<bool> WillEncryptPasswordOnFirstLogin { get; set; }
        public Nullable<bool> MustChangePasswordOnLogin { get; set; }
        public string Username { get; set; }
        public Nullable<long> CreatorPersonId { get; set; }
        public Nullable<int> IsSystemAdministrator { get; set; }
        public Nullable<int> GeneratePasswordChangeLoginTokenOnSave { get; set; }
        public string PasswordChangeLoginToken { get; set; }
        public Nullable<System.DateTime> PasswordChangeLoginTokenDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAuthorizedActivity> UserAuthorizedActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEventLog> UserEventLogs { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDataReader> CompanyDataReaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteDataReader> SiteDataReaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dashboard> Dashboards { get; set; }
    }
}
