//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Observation()
        {
            this.ObservationExceptions = new HashSet<ObservationException>();
            this.ObservationExceptions1 = new HashSet<ObservationException>();
        }
    
        public long Id { get; set; }
        public Nullable<long> TagId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> FloatValue { get; set; }
        public string TextValue { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public Nullable<long> IntegerValue { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeographicalPosition { get; set; }
        public string GoogleLatitude { get; set; }
        public string GoogleLongitude { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> DateIsUTC { get; set; }
        public Nullable<int> Quality { get; set; }
    
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservationException> ObservationExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservationException> ObservationExceptions1 { get; set; }
    }
}
