//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservationExceptionComment
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ObservationExceptionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Importance { get; set; }
        public string Comment { get; set; }
    
        public virtual ObservationException ObservationException { get; set; }
    }
}
