//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemGraphic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemGraphic()
        {
            this.SystemGraphicVisibleValues = new HashSet<SystemGraphicVisibleValue>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SystemId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual SystemGroup System { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemGraphicVisibleValue> SystemGraphicVisibleValues { get; set; }
    }
}
