//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WidgetType()
        {
            this.Widgets = new HashSet<Widget>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> InitialHeight { get; set; }
        public Nullable<int> InitialWidth { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DataTypeCode { get; set; }
        public string Description { get; set; }
        public string CategoryPath { get; set; }
        public Nullable<int> DevelopmentPriority { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> EstimatedDateOfCompletion { get; set; }
        public Nullable<long> DeveloperPersonId { get; set; }
        public string AngularDirectiveName { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<bool> IsAvailableToAdmin { get; set; }
        public Nullable<bool> IsAvailableToAll { get; set; }
        public Nullable<bool> IsHiddenSystemType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
