//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOPS_ODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Widget()
        {
            this.WidgetCustomTagDisplayOrders = new HashSet<WidgetCustomTagDisplayOrder>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> WidgetTypeId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> ParentDashboardId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> TagId { get; set; }
        public Nullable<long> SystemId { get; set; }
        public Nullable<long> SiteId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<long> EmbeddedDashboardId { get; set; }
        public Nullable<long> TerminalSystemId { get; set; }
        public Nullable<long> ZoneSystemId { get; set; }
        public Nullable<long> GateSystemId { get; set; }
        public Nullable<double> SplitLeftPercentage { get; set; }
        public Nullable<double> SplitRightPercentage { get; set; }
    
        public virtual WidgetType WidgetType { get; set; }
        public virtual Dashboard Dashboard { get; set; }
        public virtual Dashboard EmbeddedDashboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetCustomTagDisplayOrder> WidgetCustomTagDisplayOrders { get; set; }
    }
}
