//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecurityToken.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsernameHistory
    {
        public long Id { get; set; }
        public long MasterId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
