//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PersonnelEntities : DbContext
{
    public PersonnelEntities()
        : base("name=PersonnelEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ADGroup> ADGroups { get; set; }
    public virtual DbSet<Appointment> Appointments { get; set; }
    public virtual DbSet<BuildingLocation> BuildingLocations { get; set; }
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
    public virtual DbSet<Status> Status { get; set; }
    public virtual DbSet<Student> Students { get; set; }
    public virtual DbSet<UsernameHistory> UsernameHistories { get; set; }
    public virtual DbSet<Person> People { get; set; }
}
