

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class ADGroup
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ADGroup()
    {

        this.People = new HashSet<Person>();

    }


    public long Id { get; set; }

    public string Name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> People { get; set; }

}


public partial class Appointment
{

    public long Id { get; set; }

    public long MasterId { get; set; }

    public Nullable<byte> AppointmentSequence { get; set; }

    public string BusinessUnit { get; set; }

    public long DepartmentId { get; set; }

    public string Title { get; set; }

    public string JobCode { get; set; }

    public string AppointmentId { get; set; }

    public string PositionNumber { get; set; }

    public Nullable<System.DateTime> BeginDate { get; set; }

    public Nullable<System.DateTime> TerminationDate { get; set; }

    public Nullable<double> PercentTime { get; set; }

    public bool IsPrimaryJob { get; set; }



    public virtual Department Department { get; set; }

    public virtual Person Person { get; set; }

}


public partial class BuildingLocation
{

    public long MasterId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string RoomNumber { get; set; }



    public virtual Person Person { get; set; }

}


public partial class Department
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {

        this.Appointments = new HashSet<Appointment>();

    }


    public long Id { get; set; }

    public string HRDepartmentId { get; set; }

    public string Name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Appointment> Appointments { get; set; }

}


public partial class Person
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Person()
    {

        this.Appointments = new HashSet<Appointment>();

        this.Subordinates = new HashSet<Person>();

        this.PhoneNumbers = new HashSet<PhoneNumber>();

        this.UsernameHistories = new HashSet<UsernameHistory>();

        this.ADGroups = new HashSet<ADGroup>();

    }


    public long Id { get; set; }

    public long MasterId { get; set; }

    public string Username { get; set; }

    public string EmployeeID { get; set; }

    public string GivenName { get; set; }

    public string Initials { get; set; }

    public string FamilyName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Title { get; set; }

    public string DisplayNameLFM { get; set; }

    public string FullName { get; set; }

    public string StudentPID { get; set; }

    public string StudentStanding { get; set; }

    public string DoctorNumber { get; set; }

    public string Email { get; set; }

    public string ActiveDirectoryPath { get; set; }

    public string EducationAffiliation { get; set; }

    public string MailDeliveryRoute { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public string ExternalEmployeeID { get; set; }

    public string Hash { get; set; }

    public bool IsActive { get; set; }

    public bool IsPrincipalInvestigator { get; set; }

    public bool IsInstructor { get; set; }

    public Nullable<long> SupervisorMasterId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Appointment> Appointments { get; set; }

    public virtual BuildingLocation BuildingLocation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> Subordinates { get; set; }

    public virtual Person Supervisor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }

    public virtual Status Status { get; set; }

    public virtual Student Student { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsernameHistory> UsernameHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ADGroup> ADGroups { get; set; }

}


public partial class PhoneNumber
{

    public long Id { get; set; }

    public long MasterId { get; set; }

    public string Type { get; set; }

    public string Number { get; set; }

    public bool IsViewable { get; set; }



    public virtual Person Person { get; set; }

}


public partial class Status
{

    public long MasterId { get; set; }

    public bool IsUTMBEmployee { get; set; }

    public bool IsUTMBStudent { get; set; }

    public bool IsNonUTMB { get; set; }

    public bool IsNonUTMBStudent { get; set; }

    public bool IsContractor { get; set; }

    public bool IsVolunteer { get; set; }

    public bool IsActive { get; set; }

    public bool HasExternalEmployeeNumber { get; set; }



    public virtual Person Person { get; set; }

}


public partial class Student
{

    public long MasterId { get; set; }

    public string Status { get; set; }

    public Nullable<bool> HasSignedFRPA { get; set; }

    public Nullable<bool> IsMDPHD { get; set; }



    public virtual Person Person { get; set; }

}


public partial class UsernameHistory
{

    public long Id { get; set; }

    public long MasterId { get; set; }

    public string Username { get; set; }

    public Nullable<System.DateTime> InactiveDate { get; set; }



    public virtual Person Person { get; set; }

}

