

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WebSecurityEntities : DbContext
{
    public WebSecurityEntities()
        : base("name=WebSecurityEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<ExternalUser> ExternalUsers { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<ApplicationFileAttachment> ApplicationFileAttachments { get; set; }

    public virtual DbSet<SiteSourceCodeAttachment> SiteSourceCodeAttachments { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

}

