

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Activity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Activity()
    {

        this.ActivityLogs = new HashSet<ActivityLog>();

    }


    public long Id { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; }

}


public partial class ActivityLog
{

    public long Id { get; set; }

    public System.DateTime Date { get; set; }

    public long UserMasterId { get; set; }

    public Nullable<int> ApplicationId { get; set; }

    public long ActivityId { get; set; }



    public virtual Activity Activity { get; set; }

    public virtual User User { get; set; }

    public virtual Application Application { get; set; }

}


public partial class Application
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Application()
    {

        this.ActivityLogs = new HashSet<ActivityLog>();

        this.ApplicationFileAttachments = new HashSet<ApplicationFileAttachment>();

        this.Roles = new HashSet<Role>();

    }


    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActiveInProduction { get; set; }

    public bool IsActiveInTest { get; set; }

    public bool IsAvailableToAllDomainUsers { get; set; }

    public bool IsAvailableToAllUsers { get; set; }

    public Nullable<bool> NoMenu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationFileAttachment> ApplicationFileAttachments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Role> Roles { get; set; }

}


public partial class ApplicationFileAttachment
{

    public long Id { get; set; }

    public int ApplicationId { get; set; }

    public string ImageKey { get; set; }



    public virtual Application Application { get; set; }

}


public partial class ExternalUser
{

    public long UserMasterId { get; set; }

    public Nullable<long> UserId { get; set; }

    public string PasswordHash { get; set; }

    public string Organization { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Email { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }



    public virtual User User { get; set; }

}


public partial class Role
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {

        this.UserRoles = new HashSet<UserRole>();

    }


    public int Id { get; set; }

    public int ApplicationId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRoles { get; set; }

    public virtual Application Application { get; set; }

}


public partial class SiteSourceCodeAttachment
{

    public long Id { get; set; }

    public string ImageKey { get; set; }

}


public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.ActivityLogs = new HashSet<ActivityLog>();

        this.UserRoles = new HashSet<UserRole>();

    }


    public long UserMasterId { get; set; }

    public Nullable<decimal> MyUtmbUserId { get; set; }

    public string Username { get; set; }

    public string AccessToken { get; set; }

    public Nullable<System.DateTime> AccessTokenDate { get; set; }

    public Nullable<bool> IsSystemAdministrator { get; set; }

    public Nullable<bool> IsExternal { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; }

    public virtual ExternalUser ExternalUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRoles { get; set; }

}


public partial class UserRole
{

    public long Id { get; set; }

    public long UserMasterId { get; set; }

    public int RoleId { get; set; }

    public Nullable<long> CreatorMasterId { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }



    public virtual Role Role { get; set; }

    public virtual User User { get; set; }

}

