//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SignalRMessageQueue
{
    public long Id { get; set; }
    public string GroupCode { get; set; }
    public string Code { get; set; }
    public string Message { get; set; }
}

public partial class HarvestSignalRMessageQueue_Result
{
    public long Id { get; set; }
    public string GroupCode { get; set; }
    public string Code { get; set; }
    public string Message { get; set; }
}
