//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class OdataEntities : DbContext
	{
		/// <summary>
		///    DbContext to the target OData normalized model. There should be many copies of this structure. There is one on each WebAPI server in the form of a SQL Server Express or SQL server.
		/// </summary>
		/// <param name="connectionStringName" type="string">
		///     <para>
		///         Connection String Name found in the config file to which to connect.
		///     </para>
		/// </param>
		public OdataEntities(string connectionStringName)
			: base("name=" + connectionStringName)
		{
		}

	}
}
