//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models.LDAP_Cache
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string uid { get; set; }
        public string cn { get; set; }
        public string description { get; set; }
        public string displayName { get; set; }
        public string eduPersonOrgDN { get; set; }
        public string eduPersonPrimaryAffiliation { get; set; }
        public string eduPersonPrimaryOrgUnitDN { get; set; }
        public string eduPersonPrincipalName { get; set; }
        public string title { get; set; }
        public string mail { get; set; }
        public string telephonenumber { get; set; }
        public Nullable<System.DateTime> utmbDOB { get; set; }
        public string utmbCardNum { get; set; }
        public string utmbdrno { get; set; }
        public string utmbPSCode { get; set; }
        public Nullable<int> utmbemployeestatus { get; set; }
        public Nullable<int> utmbstudentstatus { get; set; }
        public Nullable<int> utmbnonustatus { get; set; }
        public int utmbuuid { get; set; }
        public Nullable<int> employeeNumber { get; set; }
        public string utmbapptid { get; set; }
        public string utmbapptjobclass { get; set; }
        public string utmbapptjobcode { get; set; }
        public string utmbapptdepartmentname { get; set; }
        public string utmbapptpsdeptid { get; set; }
        public string utmbapptprimaryjobindicator { get; set; }
        public string sn { get; set; }
        public string organizationName { get; set; }
        public string preferredLanguage { get; set; }
        public string givenname { get; set; }
        public string homePhone { get; set; }
        public string homePostalAddress { get; set; }
        public string initials { get; set; }
        public Nullable<int> utmbLibAccess { get; set; }
        public string utmbExpGradDate { get; set; }
        public string utmbFERPAPub { get; set; }
        public string utmbGradDate { get; set; }
        public string utmbPNUM { get; set; }
        public string utmbPrefix { get; set; }
        public string utmbPublish { get; set; }
        public string utmbSchoolProgram { get; set; }
        public string utmbSRID { get; set; }
        public string utmbStudStanding { get; set; }
        public string utmbVDeliveryRoute { get; set; }
        public string utmbMdPhd { get; set; }
        public string utmbJobCode { get; set; }
        public string utmbPSDeptName { get; set; }
        public string facimileTelephoneNumber { get; set; }
        public string Pager { get; set; }
        public string Mobile { get; set; }
        public string utmbBldgCode { get; set; }
        public string utmbBldgName { get; set; }
        public string roomNumber { get; set; }
        public string utmbvFax { get; set; }
        public string utmbvPhone { get; set; }
        public string utmbvpager { get; set; }
        public string utmbvmobile { get; set; }
        public string utmbBID { get; set; }
        public Nullable<int> utmb4Digits { get; set; }
        public string utmbSchool { get; set; }
        public string utmbPreferredName { get; set; }
        public string utmbSuffix { get; set; }
        public string utmbMailRoute { get; set; }
        public string utmbDeliveryRoute { get; set; }
        public string utmbvBuilding { get; set; }
        public string utmbvRoom { get; set; }
        public string utmbvMailRoute { get; set; }
        public Nullable<System.DateTime> utmbADLastLogin { get; set; }
        public Nullable<int> Active_AD_User { get; set; }
        public Nullable<int> Active_Exchange_User { get; set; }
        public string utmbRACFID { get; set; }
        public string utmbapptbegindate { get; set; }
        public string utmbapptjobtitle { get; set; }
        public string utmbapptterminationdate { get; set; }
        public string utmbapptbusinessunit { get; set; }
        public string utmbapptpositionnumber { get; set; }
        public string utmbapptpercenttime { get; set; }
        public string utmblastmodified { get; set; }
        public string utmbExtEmployeeNumber { get; set; }
    }
}
