//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMemberCatche
    {
        public string homemdb { get; set; }
        public bool isAccountDisabled { get; set; }
        public string uid { get; set; }
        public string userdn { get; set; }
        public int utmbuuid { get; set; }
        public System.DateTime whenchanged { get; set; }
        public int id { get; set; }
        public string samaccountname { get; set; }
        public string objectclass { get; set; }
        public string objectcategory { get; set; }
        public Nullable<System.Guid> objectguid { get; set; }
        public Nullable<int> userAccountControl { get; set; }
        public string cn { get; set; }
    }
}
