//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long Id { get; set; }
        public long MasterId { get; set; }
        public Nullable<byte> AppointmentSequence { get; set; }
        public string BusinessUnit { get; set; }
        public long DepartmentId { get; set; }
        public string Title { get; set; }
        public string JobCode { get; set; }
        public string AppointmentId { get; set; }
        public string PositionNumber { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<double> PercentTime { get; set; }
        public bool IsPrimaryJob { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Person Person { get; set; }
    }
}
