//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingLocation
    {
        public long MasterId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string RoomNumber { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
