//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EISTimekeeperDepartment
    {
        public string PeopleSoftDepartmentID { get; set; }
        public Nullable<int> MasterId { get; set; }
        public int Id { get; set; }
    }
}
