//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EISUsernameHistory
    {
        public string MASTERID { get; set; }
        public string OLDUSERNAME { get; set; }
        public Nullable<System.DateTime> DATERETIRED { get; set; }
        public string NEWUSERNAME { get; set; }
    }
}
