//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EISTOOLSEntities : DbContext
    {
        public EISTOOLSEntities()
            : base("name=EISTOOLSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HPRDData> HPRDDatas { get; set; }
        public virtual DbSet<EISUsernameHistory> EISUsernameHistories { get; set; }
        public virtual DbSet<Everybody> Everybodies { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<PrincipalInvestigator> PrincipalInvestigators { get; set; }
        public virtual DbSet<ADMemberCatche> ADMemberCatches { get; set; }
        public virtual DbSet<ReportsTo> ReportsToes { get; set; }
        public virtual DbSet<EISTimekeeperDepartment> EISTimekeeperDepartments { get; set; }
        public virtual DbSet<EXEMPT> EXEMPTs { get; set; }
        public virtual DbSet<PostionNumber> PostionNumbers { get; set; }
        public virtual DbSet<SHIFTELIGIBLE> SHIFTELIGIBLEs { get; set; }
    }
}
