//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPRDData
    {
        public int E1_MASTER_ID { get; set; }
        public string E1_PERS_UNIQUE_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string EMPLID { get; set; }
        public string E1_STUDNT_ID { get; set; }
        public string DEPTID { get; set; }
        public string E1_NON_U_DEPT { get; set; }
        public string E1_IS_ACTIVE_EE { get; set; }
        public string E1_IS_ACTIVE_STDNT { get; set; }
        public string E1_USERID { get; set; }
        public string E1_NAME_FORMAL { get; set; }
        public string E1_PREFERRED_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string E1_NON_U_TYPE { get; set; }
        public Nullable<System.DateTime> E1_EXPIRE_DT { get; set; }
        public Nullable<System.DateTime> E1_SIGN_DT { get; set; }
        public string E1_OU { get; set; }
        public string E1_OWNER { get; set; }
        public string LASTUPDOPRID { get; set; }
        public Nullable<System.DateTime> LASTUPDDTTM { get; set; }
    }
}
