//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Subordinates = new HashSet<Person>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
            this.UsernameHistories = new HashSet<UsernameHistory>();
            this.ADGroups = new HashSet<ADGroup>();
            this.TimekeeperDepartments = new HashSet<TimekeeperDepartment>();
            this.Providers = new HashSet<Provider>();
        }
    
        public long Id { get; set; }
        public long MasterId { get; set; }
        public string Username { get; set; }
        public string EmployeeID { get; set; }
        public string GivenName { get; set; }
        public string Initials { get; set; }
        public string FamilyName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Title { get; set; }
        public string DisplayNameLFM { get; set; }
        public string FullName { get; set; }
        public string StudentPID { get; set; }
        public string StudentStanding { get; set; }
        public string DoctorNumber { get; set; }
        public string Email { get; set; }
        public string ActiveDirectoryPath { get; set; }
        public string EducationAffiliation { get; set; }
        public string MailDeliveryRoute { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ExternalEmployeeID { get; set; }
        public string Hash { get; set; }
        public bool IsActive { get; set; }
        public bool IsPrincipalInvestigator { get; set; }
        public bool IsInstructor { get; set; }
        public Nullable<long> SupervisorMasterId { get; set; }
        public string SSNLast4 { get; set; }
        public Nullable<bool> IsShiftEligible { get; set; }
        public Nullable<bool> IsExempt { get; set; }
        public string PositionNumber { get; set; }
        public string StormStatus { get; set; }
        public Nullable<System.DateTime> StormStatusApprovedDate { get; set; }
        public string StormSkills { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual BuildingLocation BuildingLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Subordinates { get; set; }
        public virtual Person Supervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsernameHistory> UsernameHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADGroup> ADGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimekeeperDepartment> TimekeeperDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
