//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public long MasterId { get; set; }
        public bool IsUTMBEmployee { get; set; }
        public bool IsUTMBStudent { get; set; }
        public bool IsNonUTMB { get; set; }
        public bool IsNonUTMBStudent { get; set; }
        public bool IsContractor { get; set; }
        public bool IsVolunteer { get; set; }
        public bool IsActive { get; set; }
        public bool HasExternalEmployeeNumber { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
