//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDAP_Database_Cache_Update.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPRV_Provider
    {
        public string strProvider_Number { get; set; }
        public string strLast_Name { get; set; }
        public string strFirst_Name { get; set; }
        public string strMiddle_Name { get; set; }
        public string strDivision { get; set; }
        public string strDepartment { get; set; }
        public string strSpecialty_Code { get; set; }
        public string strProvider_Type { get; set; }
        public decimal numProvider_ID { get; set; }
        public Nullable<decimal> numDepartment_ID { get; set; }
        public string strDepartment_IDs { get; set; }
        public string strInvision_Name { get; set; }
        public string strSSN { get; set; }
        public string strAccounting_Period { get; set; }
        public string strBlue_Cross_Number { get; set; }
        public string strMedicaid_Number { get; set; }
        public string strAffiliation { get; set; }
        public string strLocation_Code { get; set; }
        public string strDunning_Exception { get; set; }
        public string strDEA_Number { get; set; }
        public string strUPIN { get; set; }
        public bool bitDepartment_Head { get; set; }
        public string strTelephone { get; set; }
        public string strLicense_Number { get; set; }
        public string strAdmitting_Privileges { get; set; }
        public Nullable<System.DateTime> dtmActive { get; set; }
        public Nullable<System.DateTime> dtmInactive { get; set; }
        public string strPager_Number { get; set; }
        public Nullable<System.DateTime> dtmBirth { get; set; }
        public Nullable<System.DateTime> dtmMCare_Start { get; set; }
        public string strCity { get; set; }
        public string strState { get; set; }
        public string strZip { get; set; }
        public string strAddress_Line_1 { get; set; }
        public string strFax_Number { get; set; }
        public bool bitExternal { get; set; }
        public bool bitTemporary_Entry { get; set; }
        public string strEmail { get; set; }
        public Nullable<decimal> numUpdated_User_ID { get; set; }
        public Nullable<System.DateTime> dtmLast_Updated { get; set; }
        public bool bitGeneric { get; set; }
        public Nullable<decimal> numUser_ID { get; set; }
        public string strResident_DEA_Number { get; set; }
        public string strPhysician_DPS_Number { get; set; }
        public string strNPI_Number { get; set; }
    }
}
